### ISSUE TITLE
problem with gloo-picking

### ISSUE THREAD

**Issue by rossant** [glumpy/glumpy#40]
there seems to be a wrong viewport, there's a vertical shift in picking (moving the mouse changes the color of the disc way below it)

![image](https://cloud.githubusercontent.com/assets/1942359/6906387/e02d7c02-d72e-11e4-8196-4a647ad6cb7d.png)

**Comment by rougier** [comment]
Thanks for the report. The problem is that the initial window is too big and got resized (hence the oval shape of disc markers). I have to write the resize event and resize the framebuffer according to window size.

If you want to fix temporarily, just set the initial window/framebuffer size to smaller size.

**Comment by rougier** [comment]
Fixed.
